#!/usr/bin/env python3
"""
Tips Catalog for Pillar: manuscript_drafting
"""

from __future__ import annotations

from typing import Any

MANUSCRIPT_DRAFTING_TIPS: list[dict[str, Any]] = [
    {'id': 'tip_sprint_peak_burst_management', 'engine': 'writing_sprint', 'feature': 'sprint_timer', 'subfeature': 'velocity', 'category': 'core', 'pillar': 'manuscript_drafting', 'title': 'Sprint Flow Velocity: Protect the 14-Minute Peak Burst', 'content': "Typing velocity telemetry shows peak cognitive flow typically occurs between minutes 11 and 18 of a 25-minute sprint. Never stop to look up a name or fact during this window; type '[TODO: name]' and keep typing to preserve momentum.", 'rationale': 'Context switching during flow states incurs a 10–15 minute cognitive penalty to re-enter deep drafting rhythm.', 'example': 'arcanum sprint --target 500 --time 25', 'tags': ['sprint', 'flow-state', 'productivity', 'drafting', 'wpm'], 'contexts': ['drafting', 'zen', 'cli'], 'depth': 'intermediate', 'weight': 1.1},
    {'id': 'tip_zen_typewriter_scroll_ergonomics', 'engine': 'zen_studio', 'feature': 'zen_editor', 'subfeature': 'typewriter_mode', 'category': 'core', 'pillar': 'manuscript_drafting', 'title': 'Typewriter Mode: Ergonomic Focus for Prolonged Drafting', 'content': 'In Zen Studio, enable Typewriter Mode to lock your active line to the vertical center of your monitor. This prevents neck strain from looking down at the bottom of the screen and keeps your mental focus anchored directly on the cursor.', 'rationale': 'Ergonomic gaze alignment reduces physical eye and neck fatigue during 2+ hour writing sessions.', 'example': 'arcanum studio Manuscript/', 'tags': ['zen-studio', 'typewriter', 'drafting', 'focus', 'ergonomics'], 'contexts': ['zen', 'drafting', 'cli'], 'depth': 'intermediate', 'weight': 1.0},
    {'id': 'tip_ambient_binaural_frequency_tuning', 'engine': 'ambient', 'feature': 'binaural_generator', 'subfeature': 'gamma_vs_alpha', 'category': 'utility', 'pillar': 'manuscript_drafting', 'title': 'Binaural Focus: 40 Hz Gamma for Complex Plotting, 10 Hz Alpha for Drafting', 'content': 'Use the built-in offline audio synthesizer (arcanum ambient) to generate 40 Hz Gamma waves for complex timeline and causal logic, or 10 Hz Alpha waves for relaxed, fluid creative drafting flow.', 'rationale': 'Pure algorithmic audio generation executes locally with zero external sample downloads or network dependencies.', 'example': 'arcanum ambient --profile gamma-40hz', 'tags': ['ambient', 'binaural', 'focus', 'soundscapes', 'audio'], 'contexts': ['drafting', 'zen', 'cli'], 'depth': 'intermediate', 'weight': 1.0},
    {'id': 'tip_sprint_circadian_velocity_alignment', 'engine': 'writing_sprint', 'feature': 'Productivity Heatmap', 'subfeature': 'circadian_velocity', 'category': 'core', 'pillar': 'manuscript_drafting', 'title': 'Circadian Velocity: Matching Drafting to Biological Peak Hours', 'content': 'Your writing sprint telemetry generates a 24-hour circadian productivity heatmap. Schedule raw first-draft drafting during your highest-WPM biological window (e.g. 06:30–08:30) and reserve low-velocity afternoon hours for worldbuilding lore entries.', 'rationale': 'Aligns cognitively demanding creative output with personal circadian dopamine rhythms.', 'example': 'arcanum sprint --heatmap', 'tags': ['sprint', 'circadian', 'productivity', 'analytics', 'drafting'], 'contexts': ['drafting', 'zen', 'cli'], 'depth': 'intermediate', 'weight': 1.0},
    {'id': 'tip_heatmap_perfectionist_trap_detector', 'engine': 'revision_heatmap', 'feature': 'Perfectionist Trap Detector', 'subfeature': 'perfectionist_trap', 'category': 'craft', 'pillar': 'manuscript_drafting', 'title': 'Perfectionist Trap Detector: Breaking the Chapter 1 Polish Loop', 'content': 'The revision heatmap alerts authors when Chapter 1 has undergone >15 revision cycles while middle chapters remain unwritten. It gently nudges you to freeze early chapters and focus drafting energy forward on Act II and Act III.', 'rationale': 'Prevents the common writer pitfall of endlessly polishing opening scenes at the expense of finishing the draft.', 'example': 'arcanum revision-heatmap Manuscript', 'tags': ['revision-heatmap', 'perfectionism', 'drafting', 'momentum', 'productivity'], 'contexts': ['drafting', 'revision', 'cli'], 'depth': 'intermediate', 'weight': 1.1},
    {'id': 'tip_ambient_procedural_soundscapes_infinite', 'engine': 'ambient', 'feature': 'Procedural Soundscapes', 'subfeature': 'procedural_audio', 'category': 'utility', 'pillar': 'manuscript_drafting', 'title': 'Procedural Audio Synthesis: Infinite Non-Repeating Focus Loops', 'content': 'Unlike looped MP3 files that fatigue the ear with repeating sound artifacts every 30 seconds, Ars Arcanum ambient audio generates organic pink noise, rain droplet timing, and low tavern murmur procedurally in real-time math.', 'rationale': 'Procedural audio eliminates repetitive auditory triggers that break deep concentration.', 'example': 'arcanum ambient generate tavern', 'tags': ['ambient', 'procedural-audio', 'soundscape', 'focus', 'flow-state'], 'contexts': ['drafting', 'zen', 'cli'], 'depth': 'advanced', 'weight': 1.0},
    {'id': 'tip_zen_studio_in_situ_lore_drawer_retrieval', 'engine': 'zen_studio', 'feature': 'In-Situ Lore Drawer', 'subfeature': 'in_situ_lore_drawer', 'category': 'utility', 'pillar': 'manuscript_drafting', 'title': 'In-Situ Lore Drawer: Zero-Distraction Entity Verification While Drafting', 'content': "Use Zen Studio's slide-out lore drawer (`📜 Lore Vault`) to instantly search character eye colors, weapon weights, and world rules directly beside your editor without opening external browser windows or breaking flow state.", 'rationale': 'Eliminates context-switching cognitive penalty during high-velocity prose drafting sprints.', 'example': 'arcanum zen Manuscript/ --lore Worlds/Aethelgard', 'tags': ['zen-studio', 'lore-drawer', 'in-situ', 'drafting', 'flow-state', 'in-situ-lore-drawer'], 'contexts': ['drafting', 'studio'], 'depth': 'intermediate', 'weight': 1.1},
    {'id': 'tip_tips_cross_platform_ambient_presentation', 'engine': 'tips', 'feature': 'Cross-Platform Ambient Presentation', 'subfeature': 'cross_platform_ambient_presentation', 'category': 'utility', 'pillar': 'manuscript_drafting', 'title': 'Ambient Multi-Surface Presentation: Tips in CLI, Studio Hub & Zen Studio', 'content': 'Tips are non-intrusively embedded across all surfaces: CLI terminal execution footers, Studio Hub top banner badges, and Zen Studio slide-out craft wisdom drawers.', 'rationale': 'Delivers insights ambiently at the moment of action across both terminal and GUI workflows without blocking UI interactions.', 'example': 'arcanum zen Manuscript/ --lore Worlds/Aethelgard', 'tags': ['tips', 'ambient-presentation', 'studio-hub', 'zen-studio', 'cli', 'cross-platform-ambient-presentation'], 'contexts': ['studio', 'drafting', 'cli'], 'depth': 'intermediate', 'weight': 1.0},
    {'id': 'tip_templates_manuscript_chapter_tagging', 'engine': 'structure', 'feature': 'Manuscript Tagging', 'subfeature': 'manuscript_chapter_tagging', 'category': 'craft', 'pillar': 'manuscript_drafting', 'title': 'Manuscript Scene Headers: Multi-Engine Tracking with Zero Publication Leakage', 'content': "Annotating manuscript chapters with '@pov:', '@char:', '@location:', '@time:', '@narrative_day:', '@thread:', '@scene:', and '@pacing:' activates real-time story canvas corkboards, subplot matrices, and timeline synchronizers. The publication exporter automatically strips these tags during PDF/EPUB compilation.", 'rationale': 'Provides rich planning analytics during drafting without compromising publication cleanliness.', 'example': 'arcanum plot && arcanum export Book-01', 'tags': ['templates', 'manuscript', 'tags', 'export', 'novelwriter', 'corkboard', 'manuscript-chapter-tagging'], 'contexts': ['drafting', 'structure', 'publishing', 'cli'], 'depth': 'masterclass', 'weight': 1.2},
    {'id': 'tip_templates_dwight_swain_scene_and_sequel', 'engine': 'scene_mechanics', 'feature': 'Scene & Sequel Worksheets', 'subfeature': 'dwight_swain_scene_and_sequel', 'category': 'craft', 'pillar': 'manuscript_drafting', 'title': 'Dwight Swain Scene & Sequel Worksheets: Calibrating Narrative Micro-Pacing', 'content': "Use 'Templates/Scene-Note-Template.md' and 'Outlines/Scene-Mechanics-Blueprint.md' to formally pair Action Scenes (Goal -> Conflict -> Disaster) with introspective Sequels (Reaction -> Dilemma -> Decision), ensuring chapters never stall.", 'rationale': 'Enforces continuous dramatic momentum and visceral emotional stakes across chapter transitions.', 'example': 'arcanum scene audit Manuscripts/Novel', 'tags': ['templates', 'scene-mechanics', 'dwight-swain', 'sequel', 'pacing', 'emotions', 'dwight-swain-scene-and-sequel'], 'contexts': ['drafting', 'structure', 'studio'], 'depth': 'advanced', 'weight': 1.2},
]
